/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author carlo
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTReservas = new javax.swing.JButton();
        BTGestionClientes = new javax.swing.JButton();
        BTGestionCanchas = new javax.swing.JButton();
        BTSALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setText("SISTEMA DE GESTION DE CANCHAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 580, 110));

        BTReservas.setText("RESERVAS");
        BTReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTReservasActionPerformed(evt);
            }
        });
        jPanel1.add(BTReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 160, 50));

        BTGestionClientes.setText("GESTION DE CLIENTES");
        BTGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTGestionClientesActionPerformed(evt);
            }
        });
        jPanel1.add(BTGestionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, 50));

        BTGestionCanchas.setText("GESTION DE CANCHAS");
        BTGestionCanchas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTGestionCanchasActionPerformed(evt);
            }
        });
        jPanel1.add(BTGestionCanchas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 160, 50));

        BTSALIR.setText("SALIR");
        BTSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSALIRActionPerformed(evt);
            }
        });
        jPanel1.add(BTSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 160, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTSALIRActionPerformed

    private void BTReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTReservasActionPerformed
       FReservas fr = new FReservas();
       fr.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BTReservasActionPerformed

    private void BTGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTGestionClientesActionPerformed
        FGestionClientes cl = new FGestionClientes();
        cl.setVisible(true);
        cl.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BTGestionClientesActionPerformed

    private void BTGestionCanchasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTGestionCanchasActionPerformed
        FGestionCanchas gc = new FGestionCanchas();
        gc.setVisible(true);
        gc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BTGestionCanchasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTGestionCanchas;
    private javax.swing.JButton BTGestionClientes;
    private javax.swing.JButton BTReservas;
    private javax.swing.JButton BTSALIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
